[package]
name = "validador_crate_rust"
version = "0.1.1"
edition = "2024"
authors = ["Rodrigo <dev.rodrigotlima@gmail.com>"]
description = "Criando um Crate"
license = "MIT"
repository = "https://github.com/rtlima83/validador-crate-rust"
documentation = "https://github.com/rtlima83/validador-crate-rust/blob/main/README.md"

[dependencies]
